# Generated by Django 5.2.4 on 2025-07-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('IDOperacao', models.AutoField(primary_key=True, serialize=False)),
                ('Parametros', models.CharField(max_length=255)),
                ('Resultado', models.CharField(max_length=255)),
                ('DtInclusao', models.DateTimeField(auto_now_add=True)),
                ('IDUsuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'db_table': 'Operacao',
            },
        ),
    ]
