# Generated by Django 5.2.4 on 2025-07-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Senha', models.CharField(max_length=128)),
                ('DtInclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
            },
        ),
    ]
