# Generated by Django 5.2.4 on 2025-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DtInclusao',
            field=models.DateTimeField(auto_now_add=True, db_column='DtInclusao'),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='DtInclusao',
            new_name='dt_inclusao',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(db_column='Email', max_length=255, unique=True),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='IDUsuario',
            field=models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='IDUsuario',
            new_name='id_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nome',
            field=models.CharField(db_column='Nome', max_length=255),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Senha',
            field=models.CharField(db_column='Senha', max_length=128),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Senha',
            new_name='senha',
        ),
    ]
